package com.formation.bankonet.controller;

import com.formation.bankonet.models.Client;
import com.formation.bankonet.models.CompteCourant;
import com.formation.bankonet.models.CompteEpargne;
import com.formation.bankonet.repositories.ClientRepository;
import com.formation.bankonet.repositories.CompteCourantRepository;
import com.formation.bankonet.repositories.CompteEpargneRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private ClientRepository clientRepository;
    private CompteCourantRepository compteCourantRepository;
    private CompteEpargneRepository compteEpargneRepository;


    /*
            Client Handling

            addNewClient -> POST

            getListClients -> GET

            getClient -> GET
     */
    @PostMapping(path="/addClient") // Map ONLY POST Requests
    public @ResponseBody
    String addNewClient (@RequestParam String p_nom
            , @RequestParam String p_prenom) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Client n = new Client();
        n.setNom(p_nom);
        n.setPrenom(p_prenom);
        clientRepository.save(n);
        return "Client Saved";
    }

    @GetMapping(path="/allClient")
    public @ResponseBody Iterable<Client> getListClients() {
        // This returns a JSON or XML with the users
        return clientRepository.findAll();
    }



    /*
            CompteCourant Handling

            addNewCompteCourant -> POST

            getCompteCourantList -> GET
     */
    @PostMapping(path="/addCompteCourant") // Map ONLY POST Requests
    public @ResponseBody
    String addNewCompteCourant (@RequestParam String p_intitule
            , @RequestParam int p_solde
            , @RequestParam int p_tauxInteret) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        CompteCourant n = new CompteCourant();
        n.setIntitule(p_intitule);
        n.setSolde(p_solde);
        n.setTauxInteret(p_tauxInteret);
        compteCourantRepository.save(n);
        return "Compte courant Saved";
    }

    @GetMapping(path="/allCompteCourant")
    public @ResponseBody Iterable<CompteCourant> getCompteCourantList() {
        // This returns a JSON or XML with the users
        return compteCourantRepository.findAll();
    }


    /*
            CompteEpargne Handling

            addNewCompteEpargne -> POST

            getCompteEpargneList -> GET
     */
    @PostMapping(path="/addCompteCourant") // Map ONLY POST Requests
    public @ResponseBody
    String addNewCompteEpargne (@RequestParam String p_intitule
            , @RequestParam int p_solde
            , @RequestParam int p_montantDecouvertAutorise) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        CompteEpargne n = new CompteEpargne();
        n.setIntitule(p_intitule);
        n.setSolde(p_solde);
        n.setMontantDecouvertAutorise(p_montantDecouvertAutorise);
        compteEpargneRepository.save(n);
        return "compte épargne Saved";
    }

    @GetMapping(path="/allCompteCourant")
    public @ResponseBody Iterable<CompteEpargne> getCompteEpargneList() {
        // This returns a JSON or XML with the users
        return compteEpargneRepository.findAll();
    }


}
